name: life_eazy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.90+9

environment:
   sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter

  cupertino_icons: ^1.0.2
  bubble: ^1.2.1
  intl_phone_number_input: ^0.7.1
  pin_code_fields: ^7.3.0
  stacked: ^3.0.1
  carousel_slider: ^4.0.0
  get_it: ^7.2.0
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  shared_preferences:
  firebase_auth: ^4.2.0
  flutter_svg: ^1.0.3
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  webview_flutter: ^4.0.2
  razorpay_flutter: any
#  charts_flutter: ^0.12.0
  permission_handler: ^10.1.0
  agora_rtc_engine: ^6.0.0
  uuid: ^3.0.5
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  geolocator: ^9.0.2
  image_picker: ^0.8.6
  syncfusion_flutter_signaturepad: ^20.3.47

  signature: ^5.0.0
#  image_gallery_saver:
  pdf: ^3.7.2
  cached_network_image:
  native_pdf_view: ^6.0.0+1
  printing: ^5.7.4

  path_provider: ^2.0.9
#  share: ^2.0.4
  flutter_local_notifications: ^12.0.4
  stacked_hooks: ^0.2.2
  flutter_hooks:
  package_info_plus: ^1.4.2
  share_plus: ^4.5.3
  file_picker: ^4.6.1
  open_file: ^3.2.1

 




dev_dependencies:
   flutter_test:
    sdk: flutter

dependency_overrides:
#  image_picker_android: 0.8.4+13
#  firebase_core_platform_interface: 4.5.1

#  flutter_launcher_icons: ^0.9.2
#flutter_icons:
#  image_path: "images/icon/img.png"
#  ios: true





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   -  images/dashboard/
   -  images/symptoms/
   -  images/
   -  images/empty.jpg
   -  images/introscreens/
   -  images/vector.png
   -  images/vitals/
   -  images/svg/
   -  images/immunization/
   -  images/pharmacy/
   -  images/icon/
   -  images/profile_background.jpg
